# =======================
#      BOARD SETTINGS
# =======================
board:
  - "&a%player%'s profile"
  - "&8ᴠɪᴇᴡᴇʀ: &7%viewer%"
  - ""
  - "&fKills: &c%statistic_player_kills%"
  - "&fDeaths: &6%statistic_deaths%"
  - "&fRank: %luckperms_prefix%"
  - ""
  - "&7[unsneak to hide]"

properties: 
  horizontal: 2          # Increase to move right, decrease to move left
  vertical: -1.5         # Increase to move up, decrease to move down
  scale: 1
  color: 10,0,0          # RGB color for display background (for the default transparent background, set this to DEFAULT)

# =======================
#     EVENT SETTINGS
# =======================
delay: 0                 # Delay after shifting (in ticks)

# =======================
#   VISIBILITY SETTINGS
# =======================
allow-all-worlds: true   # Enable/Disable boards in all worlds
allowed-worlds:          # List of worlds where boards are visible
  - "judge-world"

specific-regions: false  # Enable/Disable region-specific visibility
allowed-regions:         # List of WorldGuard regions where boards are visible
  - "judge-region"       # Requires the WorldGuard plugin
